# Generated by Django 3.1.3 on 2020-12-21 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0002_auto_20201220_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='create_data',
            new_name='create_date',
        ),
    ]
