# Generated by Django 3.1.3 on 2020-12-22 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0003_auto_20201221_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_data',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='update_data',
            new_name='update_date',
        ),
    ]
